### ISSUE TITLE
Google Hybrid layer only becomes invisible when new layer is loaded

### ISSUE THREAD

**Issue by erget** [openlayers/ol2#1489] opened 2016-02-17 14:59 UTC
When using [OL from the CDN](http://www.openlayers.org/api/OpenLayers.js), the Google Hybrid layer is loaded and cached but not displayed until another layer is turned on. We've confirmed this by panning and zooming when the initial map is turned on - Firefox's network analysis shows that the tiles are loaded but simply not shown. When another map is turned on, e.g. Google Satellite, it is loaded and displayed correctly. Switching back to Google Hybrid shows the hybrid layer as expected. I've seen the same problem with Google Terrain layers.

If Google Satellite is loaded ``onload``, the problem doesn't happen. Therefore it seems that Google Satellite is not affected by this problem.

[Here's an example.](http://www.andygerth.onlinehome.de/sideG.shtml)

We first registered this problem on 15 Feb 2016 - it might be that it had happened a bit earlier, but that was when it was noticed. The current workaround is to use a locally cached, older version of OL, but I'd expect this to work out of the box.

I'm not wanting to dig too deep into the library itself, but the colleague that alerted me to this problem found that there was only one difference between the new and the old script. The following line is present in the old one and missing from the new (excerpted poor man's diff from the minified version):

    + if(b.rendered)c.div.appendChild(e),b.googleControl.appendChild(c.viewPortDiv),google.maps.event.trigger(this.mapObject,"resize"
    - {if(b.rendered)b.googleControl.appendChild(c.viewPortDiv)
    ...
    - ;b.googleControl.appendChild(c.viewPortDiv)})}c.div.appendChild(e);google.maps.event.trigger(this.mapObject,"resize"

This seems to refer to [SetGMapVisibility](https://github.com/openlayers/ol2/blob/9090ad68454e43bd7301ffe15424c8bbbbe1efd2/lib/OpenLayers/Layer/Google/v3.js#L131) - perhaps in the newer version ``visibility`` is not set to ``true`` because ``cache`` isn't present?

**Comment by ahocevar** [comment] 2016-02-17 15:02
Duplicate of #1450. This has been fixed in master. Please use a local build of OpenLayers instead of the CDN version, which is 2.13.1.

**Closed by ahocevar** 2016-02-17 15:02 UTC
